# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MHKeyValueStoreDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!

  # Pods for MHKeyValueStoreDemo
  pod 'FMDB', '~> 2.7.5'
  #pod 'MHKeyValueStore'

end
